version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 1000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      node1_esnet:
        ipv4_address: 192.168.100.100

networks:
  node1_esnet:
    external: true
